# Generated by Django 3.1.2 on 2020-11-24 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20201124_1309'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='athor',
            new_name='author',
        ),
    ]
